/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SinRouteImport } from './routes/sin'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as ExportRouteImport } from './routes/export'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as IndexRouteImport } from './routes/index'

const SinRoute = SinRouteImport.update({
  id: '/sin',
  path: '/sin',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/documents': typeof DocumentsRoute
  '/export': typeof ExportRoute
  '/intake': typeof IntakeRoute
  '/pricing': typeof PricingRoute
  '/readiness': typeof ReadinessRoute
  '/registration': typeof RegistrationRoute
  '/review': typeof ReviewRoute
  '/sin': typeof SinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/documents': typeof DocumentsRoute
  '/export': typeof ExportRoute
  '/intake': typeof IntakeRoute
  '/pricing': typeof PricingRoute
  '/readiness': typeof ReadinessRoute
  '/registration': typeof RegistrationRoute
  '/review': typeof ReviewRoute
  '/sin': typeof SinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/documents': typeof DocumentsRoute
  '/export': typeof ExportRoute
  '/intake': typeof IntakeRoute
  '/pricing': typeof PricingRoute
  '/readiness': typeof ReadinessRoute
  '/registration': typeof RegistrationRoute
  '/review': typeof ReviewRoute
  '/sin': typeof SinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance'
    | '/documents'
    | '/export'
    | '/intake'
    | '/pricing'
    | '/readiness'
    | '/registration'
    | '/review'
    | '/sin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance'
    | '/documents'
    | '/export'
    | '/intake'
    | '/pricing'
    | '/readiness'
    | '/registration'
    | '/review'
    | '/sin'
  id:
    | '__root__'
    | '/'
    | '/compliance'
    | '/documents'
    | '/export'
    | '/intake'
    | '/pricing'
    | '/readiness'
    | '/registration'
    | '/review'
    | '/sin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplianceRoute: typeof ComplianceRoute
  DocumentsRoute: typeof DocumentsRoute
  ExportRoute: typeof ExportRoute
  IntakeRoute: typeof IntakeRoute
  PricingRoute: typeof PricingRoute
  ReadinessRoute: typeof ReadinessRoute
  RegistrationRoute: typeof RegistrationRoute
  ReviewRoute: typeof ReviewRoute
  SinRoute: typeof SinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sin': {
      id: '/sin'
      path: '/sin'
      fullPath: '/sin'
      preLoaderRoute: typeof SinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplianceRoute: ComplianceRoute,
  DocumentsRoute: DocumentsRoute,
  ExportRoute: ExportRoute,
  IntakeRoute: IntakeRoute,
  PricingRoute: PricingRoute,
  ReadinessRoute: ReadinessRoute,
  RegistrationRoute: RegistrationRoute,
  ReviewRoute: ReviewRoute,
  SinRoute: SinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
