/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SinRouteImport } from './routes/sin'
import { Route as ScaRouteImport } from './routes/sca'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as PricingWorkbookRouteImport } from './routes/pricing-workbook'
import { Route as MarketValidationRouteImport } from './routes/market-validation'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as ExportRouteImport } from './routes/export'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as IndexRouteImport } from './routes/index'

const SinRoute = SinRouteImport.update({
  id: '/sin',
  path: '/sin',
  getParentRoute: () => rootRouteImport,
} as any)
const ScaRoute = ScaRouteImport.update({
  id: '/sca',
  path: '/sca',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingWorkbookRoute = PricingWorkbookRouteImport.update({
  id: '/pricing-workbook',
  path: '/pricing-workbook',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketValidationRoute = MarketValidationRouteImport.update({
  id: '/market-validation',
  path: '/market-validation',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/export': typeof ExportRoute
  '/intake': typeof IntakeRoute
  '/market-validation': typeof MarketValidationRoute
  '/pricing-workbook': typeof PricingWorkbookRoute
  '/readiness': typeof ReadinessRoute
  '/registration': typeof RegistrationRoute
  '/review': typeof ReviewRoute
  '/sca': typeof ScaRoute
  '/sin': typeof SinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/export': typeof ExportRoute
  '/intake': typeof IntakeRoute
  '/market-validation': typeof MarketValidationRoute
  '/pricing-workbook': typeof PricingWorkbookRoute
  '/readiness': typeof ReadinessRoute
  '/registration': typeof RegistrationRoute
  '/review': typeof ReviewRoute
  '/sca': typeof ScaRoute
  '/sin': typeof SinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/export': typeof ExportRoute
  '/intake': typeof IntakeRoute
  '/market-validation': typeof MarketValidationRoute
  '/pricing-workbook': typeof PricingWorkbookRoute
  '/readiness': typeof ReadinessRoute
  '/registration': typeof RegistrationRoute
  '/review': typeof ReviewRoute
  '/sca': typeof ScaRoute
  '/sin': typeof SinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documents'
    | '/export'
    | '/intake'
    | '/market-validation'
    | '/pricing-workbook'
    | '/readiness'
    | '/registration'
    | '/review'
    | '/sca'
    | '/sin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documents'
    | '/export'
    | '/intake'
    | '/market-validation'
    | '/pricing-workbook'
    | '/readiness'
    | '/registration'
    | '/review'
    | '/sca'
    | '/sin'
  id:
    | '__root__'
    | '/'
    | '/documents'
    | '/export'
    | '/intake'
    | '/market-validation'
    | '/pricing-workbook'
    | '/readiness'
    | '/registration'
    | '/review'
    | '/sca'
    | '/sin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentsRoute: typeof DocumentsRoute
  ExportRoute: typeof ExportRoute
  IntakeRoute: typeof IntakeRoute
  MarketValidationRoute: typeof MarketValidationRoute
  PricingWorkbookRoute: typeof PricingWorkbookRoute
  ReadinessRoute: typeof ReadinessRoute
  RegistrationRoute: typeof RegistrationRoute
  ReviewRoute: typeof ReviewRoute
  ScaRoute: typeof ScaRoute
  SinRoute: typeof SinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sin': {
      id: '/sin'
      path: '/sin'
      fullPath: '/sin'
      preLoaderRoute: typeof SinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sca': {
      id: '/sca'
      path: '/sca'
      fullPath: '/sca'
      preLoaderRoute: typeof ScaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing-workbook': {
      id: '/pricing-workbook'
      path: '/pricing-workbook'
      fullPath: '/pricing-workbook'
      preLoaderRoute: typeof PricingWorkbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-validation': {
      id: '/market-validation'
      path: '/market-validation'
      fullPath: '/market-validation'
      preLoaderRoute: typeof MarketValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentsRoute: DocumentsRoute,
  ExportRoute: ExportRoute,
  IntakeRoute: IntakeRoute,
  MarketValidationRoute: MarketValidationRoute,
  PricingWorkbookRoute: PricingWorkbookRoute,
  ReadinessRoute: ReadinessRoute,
  RegistrationRoute: RegistrationRoute,
  ReviewRoute: ReviewRoute,
  ScaRoute: ScaRoute,
  SinRoute: SinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
